## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
arr=np.random.randint(10, size=(5))
print(arr)
filter_arr=(arr>3) & (arr<8) 
arr[filter_arr] = arr[filter_arr] * (-1)
print(arr)

**2.** Заменить максимальный элемент случайного массива на 0

In [40]:
# Variant 1 
# max_elem=arr[0]
# for elem in arr:
# 	if elem > max_elem:
# 	  max_elem = elem
# for i, elem in enumerate(arr):
# 	if elem==max_elem:
# 		arr[i]=0

# Variant 2
# max_elem=np.max(arr)
# for i, elem in enumerate(arr):
# 	if elem==max_elem:
# 		arr[i]=0

# Variant 3
arr = np.array([2, 5, 3, 5])
print(arr)
max_elem=np.max(arr)
print(max_elem)
arr[arr==max_elem]=0
print(arr)


[2 5 3 5]
5
[2 0 3 0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [ ]:
arr = np.array([[1, 2],
                [3, 4]])

# строки для комбинаций
a = arr[0]  # первая строка
b = arr[1]  # вторая строка

# сетка комбинаций
A, B = np.meshgrid(a, b)

# преобразование сетки в список пар
result = np.column_stack([A.ravel(), B.ravel()])

print("Декартово произведение:\n", result)


Декартово произведение:
 [[1 3]
 [2 3]
 [1 4]
 [2 4]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [81]:
# Variant 1
arrA=np.random.randint(5, size=(8,3))
arrB=np.random.randint(5, size=(2,2))
print(arrA)
print(arrB)
new_arr=[]
for rowA in arrA:
		if all(np.all(np.isin(rowB,rowA)) for rowB in arrB):
			new_arr.append(rowA)
print(np.array(new_arr))

[[3 4 0]
 [2 3 3]
 [1 3 4]
 [3 3 1]
 [1 1 3]
 [2 2 4]
 [3 1 2]
 [3 1 4]]
[[2 2]
 [0 1]]
[]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [ ]:
arr=np.array([
	[2, 2, 2],
 	[2, 2, 2],
 	[2, 2, 1],
 	[2, 1, 1],
 	[2, 2, 1],
 	[1, 1, 2],
 	[1, 2, 1],
 	[2, 1, 1],
 	[1, 1, 1],
 	[2, 2, 2]
	])
print("Original:\n",arr)
result=[]

# Variant 1
# for row in arr:
# 	count=0
# 	eq_value=row[0]
# 	for elem in row:
# 		if elem == eq_value:
# 			count+=1
# 	if count!=3:
# 		result.append(row)

# Variant 2
result=arr[arr.min(axis=1)!=arr.max(axis=1)]

print("Result:\n",np.array(result))



**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [ ]:
arr=np.array(
	[
	[1,2,3],
   [4,5,6],
   [1,2,3],
   [7,8,9],
   [4,5,6]
	]
)

result=np.unique(arr, axis=0)
print("Result:\n",np.array(result))

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [ ]:
################### PYTHON ######################

list_x = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
print(list_x)
list_prod=1
for i in range(min(len(list_x),len(list_x[0]))):
	if list_x[i][i]!=0:
		list_prod*=list_x[i][i]
print("Произведение ненулевых элементов на python: ", list_prod)

################### NUMPY ######################

array_x=np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(array_x)
array_prod=np.prod(np.diag(array_x)[np.diag(array_x)!=0])
print("Произведение ненулевых элементов на numpy: ", array_prod)

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [ ]:
################### PYTHON ######################

list_x = [1, 2, 2, 4]
list_y = [4, 2, 1, 2]
multiset_list=sorted(list_x)==sorted(list_y)
print(multiset_list)

################### NUMPY ######################

array_x = [1, 2, 2, 4]
array_y = [4, 2, 1, 2]
multiset_array=np.array_equal(np.sort(array_x),np.sort(array_y))
print(multiset_array)

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
################### PYTHON ######################

list_x=[6, 2, 0, 3, 0, 0, 5, 7, 0]
new_list=[]
for i, elem in enumerate(list_x):
	if i>0 and list_x[i-1]==0:
		new_list.append(elem)
print("Python: ", max(new_list))

################### NUMPY ######################

array_x=np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
result=np.max(array_x[1:][array_x[:-1]==0])
print("Numpy: ", result)

Python:  5
Numpy:  5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
################### PYTHON ######################
list_x=[2, 2, 2, 3, 3, 3, 5]
values_py=[]
counts_py=[]
count=1
current=list_x[0]

for i in range(1, len(list_x)):
	if list_x[i]==current:
		count+=1
	else:
		values_py.append(current)
		counts_py.append(count)
		count=1
		current=list_x[i]

values_py.append(current)
counts_py.append(count)

print("Python Числа: ",values_py)
print("Python Количество: ",counts_py)

################### NUMPY ######################

array_x = np.array([2, 2, 2, 3, 3, 3, 5])
diff_x=np.diff(array_x)
change_idx=np.flatnonzero(diff_x)+1
idx_boundaries = np.r_[0,change_idx,len(array_x)]
values_np=array_x[idx_boundaries[:-1]]
counts_np=np.diff(idx_boundaries)

print("Numpy Числа:", values_np)
print("Numpy Количество:", counts_np)


Python Числа:  [2, 3, 5]
Python Количество:  [3, 3, 1]
Numpy Числа: [2 3 5]
Numpy Количество: [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [72]:
import math
import time
from scipy.spatial.distance import cdist

################### PYTHON ######################

list_x=[[1,2], [3,4]]
list_y=[[0,0], [1,1], [5,5]]

#Python
start=time.time()
euclid_dist_py=[]
for x in list_x:
	row_dist=[]
	for y in list_y:
		row_dist.append(math.sqrt(sum([(xi-yi)**2 for xi, yi in zip(x,y)])))
	euclid_dist_py.append(row_dist)
end=time.time()
print("\nPython time:", end-start)
print("Матрица расстояний (Python):\n", euclid_dist_py)

################### NUMPY ######################

array_x=np.array([[1,2], [3,4]])
array_y=np.array([[0,0], [1,1], [5,5]])

start=time.time()
diff=array_x[:,np.newaxis,:]-array_y[np.newaxis, :, :]
euclid_dist_np=np.sqrt(np.sum(diff**2,axis=2))
end=time.time()
print("\nNumPy time:", end - start)
print("Матрица расстояний (NumPy):\n", euclid_dist_np)

################### SCIPY ######################

start=time.time()
euclid_dist_scipy=cdist(list_x,list_y,metric='euclidean')
end=time.time()
print("\nSciPy time:", end-start)
print("Матрица расстояний (SciPy):\n", euclid_dist_scipy)


Python time: 0.00022077560424804688
Матрица расстояний (Python):
 [[2.23606797749979, 1.0, 5.0], [5.0, 3.605551275463989, 2.23606797749979]]

NumPy time: 0.0012133121490478516
Матрица расстояний (NumPy):
 [[2.23606798 1.         5.        ]
 [5.         3.60555128 2.23606798]]

SciPy time: 0.00014209747314453125
Матрица расстояний (SciPy):
 [[2.23606798 1.         5.        ]
 [5.         3.60555128 2.23606798]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [73]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [ ]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [139]:
crunchie_calories=60
mean_calories=np.mean(calorie_stats)
print("Среднее значение калорий:", mean_calories)
average_calories=mean_calories-crunchie_calories
print("Среднее значение калорий у конкурентов выше на:", average_calories)

Среднее значение калорий: 106.88311688311688
Среднее значение калорий у конкурентов выше на: 46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [136]:
calorie_stats_sorted=np.sort(calorie_stats)
print("Сортированный массив калорий:", calorie_stats_sorted)

Сортированный массив калорий: [ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [140]:
median_calories=np.median(calorie_stats)
print("Медианное значение калорий:", median_calories)

Медианное значение калорий: 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [141]:
crunchie_calories=60
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)
percentile_value=None
nth_percentile=None

for x in range(1,101):
	percentile_value=np.percentile(calorie_stats,x)
	nth_percentile=x
	if percentile_value>crunchie_calories:
		break;

print("Наименьший процентиль выше 60 калорий:", nth_percentile)
print("Наименьшее значение процентиля выше 60 калорий:", percentile_value)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]
Наименьший процентиль выше 60 калорий: 4
Наименьшее значение процентиля выше 60 калорий: 70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [130]:
crunchie_calories=60
is_higher=calorie_stats>crunchie_calories
more_calories=len(calorie_stats[is_higher])/len(calorie_stats)*100
print("Процент хлопьев выше 60 калорий:", more_calories)

Процент хлопьев выше 60 калорий: 96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [ ]:
calorie_std=np.std(calorie_stats)
print("Стандартное отклонение калорий:", calorie_std)

#Среднее количество калорий среди конкурентов 106 с разбросом +-19, то есть большинство брендов имеет 87–125 калорий. CrunchieMunchies с 60 калориями находятся значительно ниже этого диапазона, что говорит о их низкокалорийности. Использование стандартного отклонения в анализе показывает, насколько продукт выделяется на фоне конкурентов.

Стандартное отклонение калорий: 19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
# Анализ показал, что среднее количество калорий у конкурентов составляет около 107 калорий, при этом большая часть брендов (96%) превышает 60 калорий на порцию. Медиана равна 110, а стандартное отклонение около 19 калорий, что показывает значительный разброс среди популярных брендов. Порция CrunchieMunchies с 60 калориями находится значительно ниже диапазона большинства конкурентов, что делает её особенно низкокалорийным и полезным выбором. Эти данные можно использовать в маркетинговых материалах, подчёркивая, что CrunchieMunchies не только вкусные, но и заметно легче большинства злаков на рынке, что делает их привлекательными для потребителей, следящих за питанием.